"""update users

Revision ID: 7597b0845bef
Revises: d22fe05901c7
Create Date: 2022-05-08 10:04:50.908228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7597b0845bef'
down_revision = 'd22fe05901c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
