"""test migrate add

Revision ID: 8cb5ee2f5e14
Revises: b37216d41dcc
Create Date: 2021-12-13 12:34:45.307437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb5ee2f5e14'
down_revision = 'b37216d41dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datacenter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_id_2', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datacenter', schema=None) as batch_op:
        batch_op.drop_column('test_id_2')

    # ### end Alembic commands ###
