"""test migrate del

Revision ID: 93b029d1a4a1
Revises: 8cb5ee2f5e14
Create Date: 2021-12-13 12:35:02.833202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b029d1a4a1'
down_revision = '8cb5ee2f5e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datacenter', schema=None) as batch_op:
        batch_op.drop_column('test_id_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datacenter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_id_2', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
