"""test migrate

Revision ID: b37216d41dcc
Revises: 
Create Date: 2021-12-13 12:34:11.593414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37216d41dcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datacenter', schema=None) as batch_op:
        batch_op.drop_column('test_id_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datacenter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_id_2', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
