name: Push-to-EC2

on:
  push:
    branches: [master, cicd]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Push to ec2 instance
        run: |
          git remote add prod ssh://ec2-user@54.156.105.123/home/ec2-user/cicd/flask-easyun-server.git && 
          git push prod master
